# .github/workflows/ci.yml

name: CI for Pull Requests to Develop

on:
  pull_request:
    branches:
      - develop  # Trigger the workflow on PRs targeting the develop branch

jobs:
  build-and-lint:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Specify the Node.js version you need

      # 3. Cache Node.js dependencies
      - name: Cache Node.js Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 5. Run Linting
      - name: Run Lint
        run: npm run lint

      # 6. Run Build
      - name: Run Build
        run: npm run build
