# .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed for creating releases and pushing commits/tags
      issues: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'  # Ensure Node.js version >=20.8.1
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm for authentication
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: echo npmrc
        run: cat ~/.npmrc
    
      - name: echo pwd
        run: pwd

      - name: Verify npm authentication
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
      - name: Install dependencies
        run: npm install

      - name: Run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
